# https://docs.netlify.com/configure-builds/file-based-configuration/#sample-file

[build]
  publish = "build"
  functions = "functions"
  command = "./node_modules/.bin/preact build --production --template src/index.html"

[context.production.environment]
  NODE_ENV = "production"

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200