# https://docs.netlify.com/configure-builds/file-based-configuration/#sample-file

[build]
  publish = "build"
  functions = "functions"

[context.production]
  command = "yarn build"
  environment = { NODE_ENV = "production" }

