# https://docs.netlify.com/configure-builds/file-based-configuration/#sample-file

[build]
  functions = "functions"
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  NODE_ENV = "production"

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200