# https://docs.netlify.com/configure-builds/file-based-configuration/#sample-file

[build]
  publish = "build"
  functions = "functions"
  command = "yarn build"

[context.production.environment]
  NODE_ENV = "production"
